import PageHeader from '@/components/shell/page-header';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
import ModelComparisonTable from './model-comparison-table';
import ManualChampionForm from './manual-champion-form';
import { getBacktestRuns, getChampions, getComparisonData, getModelPerformance, toComparisonSeries } from '@/lib/backtest';
import { getRole, requireUser } from '@/lib/auth';
import { getForecastRuns } from '@/lib/forecast';
import { runBacktest } from '@/app/(admin)/admin/backtest-actions';
export const dynamic='force-dynamic';
export default async function ModelComparisonPage({ searchParams }:{searchParams:Promise<{run_id?:string;item_id?:string;error?:string}>}){
  await requireUser(); const params=await searchParams; const [{rows:forecastRuns},{rows:backtestRuns,error:backtestError}]=await Promise.all([getForecastRuns(),getBacktestRuns()]); const runId=params.run_id??forecastRuns[0]?.runId; const selectedBacktest=backtestRuns.find((run)=>run.forecastRunId===runId)??backtestRuns[0]; const [{rows:performance,error:performanceError},{rows:comparison,error:comparisonError},{rows:champions,error:championError}]=await Promise.all([getModelPerformance(selectedBacktest?.backtestRunId),getComparisonData(runId,params.item_id),getChampions(params.item_id)]); const role=await getRole(); const modelIds=Array.from(new Set(comparison.map((row)=>row.modelId))); const series=toComparisonSeries(comparison);
  return <div><PageHeader eyebrow="ANALYSIS / BACKTEST" title="Model Comparison" description="저장된 Forecast와 검증기간 Actual의 성능을 비교합니다." actions={<Badge status="SAFE">SAVED RESULTS ONLY</Badge>}/>{params.error&&<p className="text-danger" role="alert">{params.error}</p>}<Panel title="Backtest 실행" meta={backtestRuns[0]?.status??'실행 이력 없음'}><div className="button-row"><form action={runBacktest}><select name="forecast_run_id" defaultValue={runId??''} aria-label="Forecast Run 선택"><option value="" disabled>Forecast Run 선택</option>{forecastRuns.filter((run)=>run.status==='SUCCESS').map((run)=><option key={run.runId} value={run.runId}>{run.runId.slice(0,8)}… · {run.dataSnapshotAt}</option>)}</select>{role?.role==='ADMIN'?<button className="ui-button ui-button-primary" type="submit">Backtest 실행</button>:<span className="muted">Backtest 실행은 ADMIN만 가능합니다.</span>}</form><a className="ui-button" href={`/api/analysis/model-comparison/export?run_id=${encodeURIComponent(runId??'')}${params.item_id?`&item_id=${encodeURIComponent(params.item_id)}`:''}`}>CSV 내보내기</a></div>{backtestError&&<p className="text-danger">{backtestError}</p>}</Panel><Panel className="section-gap" title="검증 성능 비교" meta={performance.length?`${performance.length}개 후보`:'저장 결과 없음'}>{performanceError||comparisonError||championError?<p className="text-danger">{performanceError??comparisonError??championError}</p>:!performance.length?<p className="empty-state">먼저 성공한 Forecast Run으로 Backtest를 실행하세요.</p>:<ModelComparisonTable performance={performance} champions={champions} series={series} modelIds={modelIds}/>}</Panel><Panel className="section-gap" title="현재 Champion" meta="SKU별 자동 선정 결과">{champions.length?<div className="data-table-scroll"><table className="ui-data-table"><thead><tr><th>SKU</th><th>Champion</th><th>Metric</th><th>값</th><th>선정 방식</th><th>선정 근거</th><th>수동 변경</th></tr></thead><tbody>{champions.map((row)=><tr key={row.itemId}><td>{row.itemId}</td><td>{row.championModelId}</td><td>{row.championMetric??<EmptyValue reason="METRIC_UNAVAILABLE"/>}</td><td>{row.championMetricValue??<EmptyValue reason="METRIC_VALUE_UNAVAILABLE"/>}</td><td><Badge status={row.selectionMethod==='MANUAL'?'WARNING':'SAFE'}>{row.selectionMethod??'확인 불가'}</Badge></td><td>{row.selectionReason??<EmptyValue reason="SELECTION_REASON_UNAVAILABLE"/>}</td><td>{role?.role==="ADMIN" && row.itemId && <ManualChampionForm itemId={row.itemId} rows={performance}/>}</td></tr>)}</tbody></table></div>:<p className="empty-state">아직 Champion이 선정되지 않았습니다.</p>}</Panel></div>;
}
