'use client';
import { useMemo, useState } from 'react';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
import type { DemandProfile, DemandType } from '@/lib/demand-profile-model';
const labels:Record<DemandType,string>={SMOOTH:'SMOOTH',INTERMITTENT:'INTERMITTENT',ERRATIC:'ERRATIC',LUMPY:'LUMPY'};
function typeBadge(type:DemandType|null){if(!type)return <Badge status="CALCULATION_UNAVAILABLE"/>;const status=type==='SMOOTH'?'SAFE':type==='LUMPY'?'CRITICAL':'WARNING';return <Badge status={status}>{labels[type]}</Badge>;}
function numberCell(value:number|null,reason:string){return value===null?<EmptyValue reason={reason}/>:value.toFixed(2);}
export default function DemandProfileTable({rows}:{rows:DemandProfile[]}){
  const [type,setType]=useState('ALL');const [availability,setAvailability]=useState('ALL');const [search,setSearch]=useState('');
  const filtered=useMemo(()=>rows.filter((row)=>{const typeOk=type==='ALL'||row.demandType===type;const availableOk=availability==='ALL'||(availability==='AVAILABLE'?row.demandType!==null:row.demandType===null);const term=search.trim().toLowerCase();return typeOk&&availableOk&&(!term||row.itemId.toLowerCase().includes(term)||(row.itemName??'').toLowerCase().includes(term));}),[rows,type,availability,search]);
  return <><div className="filter-bar"><label>Demand Type<select value={type} onChange={(event)=>setType(event.target.value)}><option value="ALL">전체</option><option value="SMOOTH">SMOOTH</option><option value="INTERMITTENT">INTERMITTENT</option><option value="ERRATIC">ERRATIC</option><option value="LUMPY">LUMPY</option></select></label><label>계산 상태<select value={availability} onChange={(event)=>setAvailability(event.target.value)}><option value="ALL">전체</option><option value="AVAILABLE">계산 가능</option><option value="UNAVAILABLE">계산 불가</option></select></label><label>SKU 검색<input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="SKU 또는 품목명" /></label></div><div className="data-table-scroll"><table className="ui-data-table"><thead><tr><th>SKU</th><th>품목명</th><th>ADI</th><th>CV²</th><th>Zero-demand Rate</th><th>Trend</th><th>Demand Type</th><th>Seasonality</th><th>Reason</th></tr></thead><tbody>{filtered.map((row)=><tr key={row.itemId}><td>{row.itemId}</td><td>{row.itemName??<EmptyValue reason="ITEM_NAME_UNAVAILABLE"/>}</td><td>{numberCell(row.adi,'ADI_UNAVAILABLE')}</td><td>{numberCell(row.cvSquared,'CV_SQUARED_UNAVAILABLE')}</td><td>{row.zeroDemandRate===null?<EmptyValue reason="ZERO_RATE_UNAVAILABLE"/>:(row.zeroDemandRate*100).toFixed(1)+'%'}</td><td>{numberCell(row.trend,'TREND_UNAVAILABLE')}</td><td>{typeBadge(row.demandType)}</td><td>{row.seasonality===null?<EmptyValue reason={row.nPeriods!==null&&row.nPeriods<24?'INSUFFICIENT_PERIODS':'SEASONALITY_UNAVAILABLE'}/>:row.seasonality?'있음':'없음'}</td><td>{row.reasonCode??'—'}</td></tr>)}</tbody></table>{filtered.length===0&&<p className="empty-state">조건에 맞는 SKU가 없습니다.</p>}</div></>;
}
