'use client';
import { useEffect, useState } from 'react';
import Panel from '@/components/ui/panel';
import Button from '@/components/ui/button';
import Badge from '@/components/ui/badge';
import { getFields } from '@/lib/import/schema';
import { IMPORT_TYPES, type ColumnMapping, type ImportMode, type ImportType } from '@/lib/import/types';

type Batch = { batch_id:string; file_name:string; import_type:string; import_mode:string; total_rows:number; success_rows:number; warning_rows:number; error_rows:number; status:string; uploaded_at:string; rollback_supported:boolean };
type Preview = { batchId:string; headers:string[]; mapping:ColumnMapping[]; preview:Record<string,unknown>[]; totalRows:number };
export default function ImportWizard() {
  const [file,setFile]=useState<File|null>(null); const [type,setType]=useState<ImportType>('usage_history'); const [mode,setMode]=useState<ImportMode>('append');
  const [preview,setPreview]=useState<Preview|null>(null); const [mapping,setMapping]=useState<ColumnMapping[]>([]); const [result,setResult]=useState<{status:string;counts:{success:number;warning:number;error:number};batchId:string}|null>(null);
  const [history,setHistory]=useState<Batch[]>([]); const [message,setMessage]=useState('');
  const loadHistory=()=>fetch('/api/admin/import/history').then((response)=>response.ok?response.json():[]).then(setHistory).catch(()=>setHistory([]));
  useEffect(()=>{loadHistory();},[]);
  async function parse() { if(!file)return; setMessage('파일을 파싱하고 있습니다.'); const form=new FormData(); form.append('file',file); form.append('import_type',type); form.append('import_mode',mode); const response=await fetch('/api/admin/import/parse',{method:'POST',body:form}); const body=await response.json(); if(!response.ok){setMessage(body.error??'파싱에 실패했습니다.');return;} setPreview(body); setMapping(body.mapping); setResult(null); setMessage('Preview와 매핑을 확인한 뒤 Validation을 실행하세요.'); }
  async function commitBatchId(batchId:string) { setMessage("RAW 적재를 처리하고 있습니다."); try { const response=await fetch("/api/admin/import/commit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({batch_id:batchId})}); const raw=await response.text(); let body:{error?:string}={}; try { body=JSON.parse(raw); } catch { body={error:raw || "서버 응답을 읽지 못했습니다."}; } setMessage(response.ok ? "RAW 적재가 완료되었습니다." : body.error ?? "적재에 실패했습니다."); loadHistory(); } catch { setMessage("서버에 연결하지 못했습니다. 개발 서버 상태를 확인하세요."); } }
  async function validate() { if(!preview)return; setMessage('Validation을 실행하고 있습니다.'); const response=await fetch('/api/admin/import/validate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({batch_id:preview.batchId,mapping})}); const body=await response.json(); if(!response.ok){setMessage(body.error??'검증에 실패했습니다.');return;} setResult(body); setMessage(body.status==='ERROR'?'오류를 수정한 파일을 다시 업로드하세요.':'검증이 완료되었습니다. 정상·경고 행을 승인할 수 있습니다.'); loadHistory(); }
  async function commit() { if(!result||result.status==='ERROR')return; const response=await fetch('/api/admin/import/commit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({batch_id:result.batchId})}); const body=await response.json(); setMessage(response.ok?'RAW 적재가 완료되었습니다.':body.error??'적재에 실패했습니다.'); loadHistory(); }
  async function rollback(batchId:string) { const response=await fetch('/api/admin/import/rollback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({batch_id:batchId})}); setMessage(response.ok?'Rollback 완료되었습니다.':(await response.json()).error??'Rollback에 실패했습니다.'); loadHistory(); }
  return <div className="stack"><Panel title="1. 파일 선택"><div className="form-grid"><label>파일<input type="file" accept=".csv,.xlsx" onChange={(event)=>setFile(event.target.files?.[0]??null)} /></label><label>데이터 종류<select value={type} onChange={(event)=>setType(event.target.value as ImportType)}>{IMPORT_TYPES.map((item)=><option key={item} value={item}>{item}</option>)}</select></label><label>Import 모드<select value={mode} onChange={(event)=>setMode(event.target.value as ImportMode)}><option value="append">append</option><option value="upsert">upsert</option><option value="replace" disabled>replace (운영 제한)</option></select></label><Button type="button" variant="primary" onClick={parse} disabled={!file}>Parse</Button></div><p className="muted">replace는 기존 데이터 전체 교체와 완전 rollback 제한이 있어 별도 유지보수 절차가 필요합니다.</p></Panel>
  {preview&&<Panel title="2. Preview / Column Mapping"><p className="muted">{preview.totalRows}행 · 원본 컬럼은 staging에 보존됩니다.</p><div className="mapping-list">{mapping.map((entry,index)=><label key={entry.source}>{entry.source}<select value={entry.target} onChange={(event)=>setMapping((items)=>items.map((item,itemIndex)=>itemIndex===index?{...item,target:event.target.value}:item))}><option value="">연결 안 함</option>{getFields(type).map((field)=><option key={field.name} value={field.name}>{field.name}</option>)}</select></label>)}</div><div className="import-preview">{preview.preview.slice(0,8).map((row,index)=><pre key={index}>{JSON.stringify(row)}</pre>)}</div><Button type="button" onClick={validate}>Validation</Button></Panel>}
  {result&&<Panel title="3. Validation Result"><div className="settings-row"><span>결과</span><Badge status={result.status==='ERROR'?'CRITICAL':result.status==='WARNING'?'WARNING':'SAFE'}>{result.status}</Badge></div><div className="settings-row"><span>행 수</span><strong>성공 {result.counts.success} · 경고 {result.counts.warning} · 오류 {result.counts.error}</strong></div><div className="page-actions"><a className="ui-button" href={'/api/admin/import/errors?batch_id='+result.batchId}>오류 CSV 다운로드</a><Button type="button" variant="primary" disabled={result.status==='ERROR'} onClick={commit}>사용자 승인 후 RAW Import</Button></div></Panel>}
  {message&&<p className="muted" role="status">{message}</p>}<Panel title="Import History"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>파일</th><th>타입</th><th>모드</th><th>행</th><th>상태</th><th>시간</th><th /></tr></thead><tbody>{history.map((item)=><tr key={item.batch_id}><td>{item.file_name}</td><td>{item.import_type}</td><td>{item.import_mode}</td><td>{item.total_rows}</td><td>{item.status}</td><td>{new Date(item.uploaded_at).toLocaleString('ko-KR')}</td><td>{item.status==="VALIDATED" ? <Button type="button" variant="primary" onClick={() => commitBatchId(item.batch_id)}>Import</Button> : item.status==="IMPORTED"&&item.rollback_supported ? <Button type="button" variant="danger" onClick={() => rollback(item.batch_id)}>Rollback</Button> : null}</td></tr>)}</tbody></table></div></Panel></div>;
}
