import { createSupabaseServerClient } from './supabase/server';
import { buildComparisonSeries, normalizeChampionRow, normalizePerformanceRow, type ChampionRow, type ComparisonInput, type PerformanceRow } from './backtest-model';

export type BacktestRun = { backtestRunId: string; forecastRunId: string; testStart: string | null; testEnd: string | null; metric: string | null; status: string; startedAt: string | null; finishedAt: string | null; message: string | null };
export type ComparisonRow = ComparisonInput & { itemId: string | null;  runId: string; modelVersion: string | null; isChampion: boolean | null };
function value(row: Record<string, unknown>, key: string) { return row[key] === undefined || row[key] === null ? null : row[key]; }
function text(row: Record<string, unknown>, key: string) { const v = value(row, key); return v === null ? null : String(v); }
function bool(row: Record<string, unknown>, key: string) { const v = value(row, key); return typeof v === 'boolean' ? v : null; }
function normalizeRun(row: Record<string, unknown>): BacktestRun { return { backtestRunId: text(row, 'backtest_run_id') ?? 'UNKNOWN', forecastRunId: text(row, 'forecast_run_id') ?? 'UNKNOWN', testStart: text(row, 'test_start'), testEnd: text(row, 'test_end'), metric: text(row, 'metric'), status: text(row, 'status') ?? 'FAILED', startedAt: text(row, 'started_at'), finishedAt: text(row, 'finished_at'), message: text(row, 'message') }; }
export async function getBacktestRuns() { const s=await createSupabaseServerClient(); const {data,error}=await s.schema('analytics').from('v_backtest_run').select('*').order('started_at',{ascending:false}); return {rows:error?[]:(data??[]).map(r=>normalizeRun(r as Record<string,unknown>)),error:error?.message??null}; }
export async function getModelPerformance(backtestRunId?:string):Promise<{rows:PerformanceRow[];error:string|null}> { const s=await createSupabaseServerClient(); let q=s.schema('analytics').from('v_model_performance').select('*').order('item_id').order('rank'); if(backtestRunId) q=q.eq('backtest_run_id',backtestRunId); const {data,error}=await q; return {rows:error?[]:(data??[]).map(r=>normalizePerformanceRow(r as Record<string,unknown>)),error:error?.message??null}; }
export async function getChampions(itemId?:string):Promise<{rows:ChampionRow[];error:string|null}> { const s=await createSupabaseServerClient(); let q=s.schema('analytics').from('v_champion_model').select('*').order('item_id'); if(itemId) q=q.eq('item_id',itemId); const {data,error}=await q; return {rows:error?[]:(data??[]).map(r=>normalizeChampionRow(r as Record<string,unknown>)),error:error?.message??null}; }
export async function getComparisonData(runId?:string,itemId?:string):Promise<{rows:ComparisonRow[];error:string|null}> { const s=await createSupabaseServerClient(); let q=s.schema('analytics').from('v_model_comparison').select('*').order('period').order('item_id').order('model_id'); if(runId) q=q.eq('run_id',runId); if(itemId) q=q.eq('item_id',itemId); const {data,error}=await q; return {rows:error?[]:(data??[]).map((r)=>{const row=r as Record<string,unknown>;return {itemId:text(row,'item_id'),runId:text(row,'run_id')??'',period:text(row,'period')??'',actual:value(row,'actual')===null?null:Number(value(row,'actual')),modelId:text(row,'model_id')??'',modelVersion:text(row,'model_version'),p50:value(row,'p50')===null?null:Number(value(row,'p50')),p80:value(row,'p80')===null?null:Number(value(row,'p80')),p90:value(row,'p90')===null?null:Number(value(row,'p90')),isChampion:bool(row,'is_champion')};}),error:error?.message??null}; }
export function toComparisonSeries(rows:ComparisonRow[]){ return buildComparisonSeries(rows); }
export async function getCsvRows(runId?:string,itemId?:string){ const [{rows:performance},{rows:comparison}]=await Promise.all([getModelPerformance(),getComparisonData(runId,itemId)]); return {performance,comparison}; }
