import { requireAdmin } from '@/lib/auth';
import { getForecastResults, getForecastRuns, getForecastRunKpi } from '@/lib/forecast';
import PageHeader from '@/components/shell/page-header';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
import RunActions from './run-actions';

export default async function ForecastRunsPage({ searchParams }: { searchParams: Promise<{ run_id?: string; error?: string; ran?: string }> }) {
  await requireAdmin(); const { rows, error } = await getForecastRuns(); const params = await searchParams; const selectedId = params.run_id ?? rows[0]?.runId ?? null;
  const results = selectedId ? await getForecastResults(selectedId) : { rows: [], error: null }; const kpi = selectedId ? await getForecastRunKpi(selectedId) : { rows: [], error: null };
  return <div><PageHeader eyebrow="ADMIN / FORECAST" title="Forecast 실행 이력" description="저장된 실행 결과를 조회하고 새 SQL Baseline 실행을 시작합니다." />{params.error && <p className="text-danger" role="alert">Forecast 실행 오류: {params.error}</p>}<div className="button-row"><RunActions /></div><Panel title="실행 이력" meta={error ? '조회 오류' : `${rows.length}건`}>
    {error ? <p className="text-danger">실행 이력을 불러오지 못했습니다: {error}</p> : rows.length === 0 ? <p className="muted">아직 실행 이력이 없습니다.</p> : <div className="data-table-scroll"><table className="ui-data-table"><thead><tr><th>Run ID</th><th>상태</th><th>실행 시간</th><th>모델 수</th><th>SKU 수</th><th>결과 행</th><th>Snapshot</th><th>Stale</th><th>실행자</th></tr></thead><tbody>{rows.map((run) => <tr key={run.runId}><td><a href={`/admin/forecast-runs?run_id=${encodeURIComponent(run.runId)}`}>{run.runId.slice(0, 8)}…</a></td><td><Badge status={run.status === 'SUCCESS' ? 'SAFE' : run.status === 'RUNNING' ? 'WARNING' : 'CRITICAL'}>{run.status}</Badge></td><td>{run.dataSnapshotAt ?? <EmptyValue reason="NO_TIMESTAMP" />}</td><td>{run.nModels ?? <EmptyValue reason="NO_MODEL_COUNT" />}</td><td>{run.nItems ?? <EmptyValue reason="NO_ITEM_COUNT" />}</td><td>{run.nRows ?? <EmptyValue reason="NO_RESULT_COUNT" />}</td><td>{run.dataSnapshotAt ?? <EmptyValue reason="NO_SNAPSHOT" />}</td><td><Badge status={run.isStale === true ? 'WARNING' : run.isStale === false ? 'SAFE' : 'CALCULATION_UNAVAILABLE'}>{run.isStale === true ? '최신 데이터 있음' : run.isStale === false ? '최신' : '확인 불가'}</Badge></td><td>{run.triggeredEmail ?? <EmptyValue reason="NO_EXECUTOR" />}</td></tr>)}</tbody></table></div>}
  </Panel><Panel title="선택 실행 결과" meta={selectedId ? selectedId.slice(0, 8) : undefined}>{results.error ? <p className="text-danger">결과를 불러오지 못했습니다: {results.error}</p> : !selectedId ? <p className="muted">실행을 선택하세요.</p> : results.rows.length === 0 ? <p className="muted">저장된 결과 행이 없습니다. 데이터 부족 모델은 결과 행을 만들지 않습니다.</p> : <><p className="muted">KPI: {JSON.stringify(kpi.rows[0] ?? {})}</p><div className="data-table-scroll"><table className="ui-data-table"><thead><tr><th>SKU</th><th>모델</th><th>기간</th><th>P50</th><th>P80</th><th>P90</th><th>Sigma</th><th>사유</th></tr></thead><tbody>{results.rows.slice(0, 200).map((result) => { const row = result; return <tr key={`${row.modelId}-${row.itemId}-${row.period}`}><td>{row.itemId ?? <EmptyValue reason="NO_ITEM" />}</td><td>{row.modelId ?? <EmptyValue reason="NO_MODEL" />}<br /><span className="muted">v{row.modelVersion ?? '—'}</span></td><td>{row.period ?? <EmptyValue reason="NO_PERIOD" />}</td><td>{row.p50 ?? <EmptyValue reason={row.reasonCode ?? 'P50_UNAVAILABLE'} />}</td><td>{row.p80 ?? <EmptyValue reason={row.sigma === null ? 'SIGMA_UNAVAILABLE' : 'P80_UNAVAILABLE'} />}</td><td>{row.p90 ?? <EmptyValue reason={row.sigma === null ? 'SIGMA_UNAVAILABLE' : 'P90_UNAVAILABLE'} />}</td><td>{row.sigma ?? <EmptyValue reason="SIGMA_UNAVAILABLE" />}</td><td>{row.reasonCode ?? '—'}</td></tr>; })}</tbody></table></div></>}</Panel></div>;
}
