import { AlertTriangle, Calculator, CheckCircle2, CircleDollarSign, Package, ShoppingCart } from 'lucide-react';
import StepFrame from './step-frame';

export default function CalculationStep({ onNext, onBack }: { onNext: () => void; onBack: () => void }) {
  return <StepFrame onNext={onNext} onBack={onBack} nextLabel="보고자료 확인"><div className="page-heading"><div><div className="eyebrow">04 / ORDER CALCULATION</div><h2>발주량 계산 및 예외 검토</h2><p>현재는 계산 결과의 구조와 예외 흐름을 확인하는 샘플 화면입니다.</p></div><span className="tag amber">상세 계산 Phase 2</span></div>
    <div className="grid grid-4"><div className="card metric"><div className="metric-label">기기 최종 발주량</div><div className="metric-value">140<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot">MOQ 적용 샘플</div></div><div className="card metric"><div className="metric-label">옵션·부품 발주량</div><div className="metric-value">142<span style={{ fontSize: 15, fontWeight: 600 }}>EA</span></div><div className="metric-foot">BOM·장착율 기반</div></div><div className="card metric"><div className="metric-label">총 발주금액</div><div className="metric-value">₩107.2M</div><div className="metric-foot good">샘플 계산 결과</div></div><div className="card metric"><div className="metric-label">예외품목</div><div className="metric-value">2<span style={{ fontSize: 15, fontWeight: 600 }}>건</span></div><div className="metric-foot warn">Flex 1 · MOQ 1</div></div></div>
    <div className="section card"><div className="card-title"><h3>발주량 계산 결과 미리보기</h3><span><Calculator size={13} /> 계산 버전 v0.1</span></div><div className="table-wrap"><table><thead><tr><th>구분</th><th>품목</th><th className="num">확정수요</th><th className="num">가용재고</th><th className="num">순소요량</th><th className="num">최종발주량</th><th>예외</th></tr></thead><tbody><tr><td>기기</td><td><b>PRT-A3-001</b><br /><span className="muted">A3 Printer Model A</span></td><td className="num">120</td><td className="num">35</td><td className="num">75</td><td className="num"><b>80</b></td><td><span className="tag green"><CheckCircle2 size={11} /> 정상</span></td></tr><tr><td>옵션</td><td><b>OPT-001</b><br /><span className="muted">Finisher X</span></td><td className="num">30</td><td className="num">18</td><td className="num">27</td><td className="num"><b>30</b></td><td><span className="tag green"><CheckCircle2 size={11} /> 정상</span></td></tr><tr><td>부품</td><td><b>PART-009</b><br /><span className="muted">필수 설치 Kit Z</span></td><td className="num">20</td><td className="num">8</td><td className="num">27</td><td className="num"><b>30</b></td><td><span className="tag red"><AlertTriangle size={11} /> Flex 초과</span></td></tr></tbody></table></div></div>
    <div className="section grid grid-2"><div className="card"><div className="card-title"><h3>예외 검토 순서</h3><span>확정 전 필수</span></div><div className="checklist">{[['Flexibility Rule 초과', '사유 및 예외승인 확인', 'red'], ['MOQ 적용 과잉', '초과수량·금액 검토', 'amber'], ['납기 부족·미확정', 'Supplier 확인 필요', 'amber']].map(([title, desc, tone]) => <div className="check-row" key={title}><div className="check-label"><span className={`check-icon ${tone === 'red' ? 'pending' : ''}`}><AlertTriangle size={12} /></span><div><b>{title}</b><br /><span className="muted" style={{ fontSize: 10 }}>{desc}</span></div></div><span className={`tag ${tone}`}>검토</span></div>)}</div></div><div className="card"><div className="card-title"><h3>수동 조정</h3><span>Phase 2에서 활성화</span></div><div className="callout"><ShoppingCart size={16} /><div><strong>계산량과 최종량을 분리 저장</strong>조정수량, 조정사유, 조정자, 조정일시를 함께 기록하는 구조입니다.</div></div><button className="button" disabled style={{ marginTop: 15 }}><Package size={14} /> 발주량 조정 기능</button></div></div>
  </StepFrame>;
}
