'use client';

import { useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, Check, CheckCircle2, ChevronDown, FileSpreadsheet, MessageSquare, Plus, Save, Search, Upload } from 'lucide-react';
import StepFrame from './step-frame';

type DemandStatus = '확정 후보' | '조건부' | '참고' | '제외';
type DemandRow = { id: number; needMonth: string; department: string; model: string; item: string; itemName: string; quantity: number; status: DemandStatus; note: string };
type SfdcRow = { id: number; dealId: string; customer: string; model: string; quantity: number; probability: number; status: string };
type BulkRow = { id: number; dealId: string; customer: string; model: string; quantity: number; needMonth: string; secured: boolean; status: DemandStatus };

const months = Array.from({ length: 12 }, (_, i) => `2025-${String(i + 1).padStart(2, '0')}`);
const baseOl: DemandRow[] = [
  { id: 1, needMonth: '2025-01', department: '직판1팀', model: 'PRT-A3-001', item: 'PRT-A3-001', itemName: 'A3 Printer Model A', quantity: 94, status: '확정 후보', note: '영업부서 OL' },
  { id: 2, needMonth: '2025-01', department: '직판2팀', model: 'PRT-A4-002', item: 'PRT-A4-002', itemName: 'A4 Printer Model B', quantity: 69, status: '확정 후보', note: '영업부서 OL' },
  { id: 3, needMonth: '2025-01', department: '파트너팀', model: 'PRT-A3-003', item: 'PRT-A3-003', itemName: 'A3 Printer Model C', quantity: 52, status: '조건부', note: '파트너 채널 전망' },
  { id: 4, needMonth: '2025-01', department: '직판1팀', model: 'PRT-A4-004', item: 'PRT-A4-004', itemName: 'A4 Printer Model D', quantity: 39, status: '참고', note: '전년 Trend 확인 필요' },
  { id: 5, needMonth: '2025-01', department: '직판1팀', model: 'PRT-A3-001', item: 'OPT-001', itemName: 'Finisher X', quantity: 29, status: '확정 후보', note: '장착율 반영 예정' },
  { id: 6, needMonth: '2025-01', department: '직판2팀', model: 'PRT-A4-002', item: 'OPT-002', itemName: 'Common Tray Y', quantity: 41, status: '확정 후보', note: 'Common품' },
];

const statusClass: Record<DemandStatus, string> = { '확정 후보': 'green', 조건부: 'amber', 참고: 'blue', 제외: 'gray' };

function monthRows(month: string) { return baseOl.map((row, index) => ({ ...row, id: row.id + Number(month.slice(-2)) * 10, needMonth: month, quantity: Math.max(3, row.quantity + ((Number(month.slice(-2)) + index) % 5 - 2) * 3) })); }

export default function DemandStep({ onNext, onBack }: { onNext: () => void; onBack: () => void }) {
  const [selectedMonth, setSelectedMonth] = useState('2025-01');
  const [tab, setTab] = useState<'ol' | 'sfdc' | 'bulk' | 'trend' | 'meeting'>('ol');
  const [olRows, setOlRows] = useState<DemandRow[]>(monthRows('2025-01'));
  const [sfdcRows, setSfdcRows] = useState<SfdcRow[]>([
    { id: 1, dealId: 'DEAL-25-01-A', customer: '고객사 01A', model: 'PRT-A3-001', quantity: 24, probability: 75, status: 'Proposal' },
    { id: 2, dealId: 'DEAL-25-01-B', customer: '고객사 01B', model: 'PRT-A4-002', quantity: 17, probability: 55, status: 'Negotiation' },
  ]);
  const [bulkRows, setBulkRows] = useState<BulkRow[]>([
    { id: 1, dealId: 'BULK-25-01', customer: 'Bulk 고객 01', model: 'PRT-A3-001', quantity: 60, needMonth: '2025-01', secured: false, status: '조건부' },
  ]);
  const [meeting, setMeeting] = useState({ date: '2025-01-15', attendees: '영업·수급·구매', decision: '확정수요와 Bulk-deal 사전재고 확보 여부를 검토합니다.', secured: false });
  const [validation, setValidation] = useState<'idle' | 'done'>('idle');
  const [confirmed, setConfirmed] = useState(false);
  const [notice, setNotice] = useState('');

  const olTotal = useMemo(() => olRows.filter((row) => row.status !== '제외').reduce((sum, row) => sum + row.quantity, 0), [olRows]);
  const sfdcTotal = useMemo(() => sfdcRows.reduce((sum, row) => sum + row.quantity * (row.probability / 100), 0), [sfdcRows]);
  const bulkTotal = useMemo(() => bulkRows.reduce((sum, row) => sum + row.quantity * (row.status === '확정 후보' ? 1 : row.status === '조건부' ? 0.5 : 0), 0), [bulkRows]);
  const invalidCount = olRows.filter((row) => !row.needMonth || !row.item || row.quantity <= 0).length;
  const confirmedDemand = Math.round(olTotal + sfdcTotal + bulkTotal);

  const changeMonth = (month: string) => { setSelectedMonth(month); setOlRows(monthRows(month)); setConfirmed(false); setValidation('idle'); setNotice(''); };
  const updateOl = (id: number, key: keyof DemandRow, value: string) => setOlRows((rows) => rows.map((row) => row.id === id ? { ...row, [key]: key === 'quantity' ? Number(value) : value } as DemandRow : row));
  const updateSfdc = (id: number, key: keyof SfdcRow, value: string) => setSfdcRows((rows) => rows.map((row) => row.id === id ? { ...row, [key]: key === 'quantity' || key === 'probability' ? Number(value) : value } as SfdcRow : row));
  const validateDemand = () => { setValidation('done'); setNotice(invalidCount ? `검증 완료: 오류 ${invalidCount}건을 수정해주세요.` : '검증 완료: 필수 입력값과 수량 형식이 정상입니다.'); };
  const confirmDemand = () => { if (validation !== 'done' || invalidCount > 0) { setNotice('먼저 검증 실행을 완료하고 오류를 수정해주세요.'); return; } setConfirmed(true); setNotice(`수요 확정 완료: ${selectedMonth} 확정수요 ${confirmedDemand.toLocaleString()}대`); };
  const addOlRow = () => setOlRows((rows) => [...rows, { id: Date.now(), needMonth: selectedMonth, department: '직접입력', model: '', item: '', itemName: '', quantity: 0, status: '참고', note: '' }]);

  return <StepFrame onNext={onNext} onBack={onBack} nextLabel="재고·공급으로 이동"><div className="page-heading"><div><div className="eyebrow">01 / DEMAND CONFIRMATION</div><h2>수요 입력 및 확정</h2><p>OL을 기준으로 SFDC, Bulk-deal, 과거 Trend와 수급회의 결과를 반영합니다.</p></div><span className={`tag ${confirmed ? 'green' : 'amber'}`}>{confirmed ? '수요 확정 완료' : '수급회의 확정 대기'}</span></div>
    <div className="demand-toolbar card"><div className="toolbar-group"><label htmlFor="demand-month">대상월도</label><select id="demand-month" value={selectedMonth} onChange={(event) => changeMonth(event.target.value)}>{months.map((month) => <option key={month}>{month}</option>)}</select></div><div className="toolbar-divider" /><div className="toolbar-summary"><span>OL 대상행 <b>{olRows.length}건</b></span><span>검증 오류 <b className={invalidCount ? 'text-danger' : 'text-good'}>{invalidCount}건</b></span><span>확정수요 <b>{confirmedDemand.toLocaleString()}대</b></span></div><div className="button-row"><button className="button" onClick={validateDemand}><Search size={14} /> 검증 실행</button><button className="button primary" onClick={confirmDemand}><Check size={14} /> 수요 확정</button></div></div>
    {notice && <div className={`callout ${invalidCount && validation === 'done' ? '' : 'blue'}`} style={{ marginTop: 14 }}><MessageSquare size={16} /><div>{notice}</div></div>}
    <div className="section grid grid-4"><div className="card metric"><div className="metric-label">OL 수요</div><div className="metric-value">{olTotal.toLocaleString()}<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot">제외 상태 제외</div></div><div className="card metric"><div className="metric-label">SFDC 반영 후보</div><div className="metric-value">{Math.round(sfdcTotal).toLocaleString()}<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot">수주확률 가중</div></div><div className="card metric"><div className="metric-label">Bulk-deal 반영</div><div className="metric-value">{Math.round(bulkTotal).toLocaleString()}<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot">사전재고 여부 검토</div></div><div className="card metric"><div className="metric-label">최종 확정 후보</div><div className="metric-value">{confirmedDemand.toLocaleString()}<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot good">확정수요 계산 미리보기</div></div></div>
    <div className="section card"><div className="demand-tabs">{[['ol','OL 취합'],['sfdc','SFDC Pipeline'],['bulk','Bulk-deal'],['trend','실적 Trend'],['meeting','수급회의']].map(([key,label]) => <button key={key} className={`demand-tab ${tab === key ? 'active' : ''}`} onClick={() => setTab(key as typeof tab)}>{label}</button>)}</div>
      {tab === 'ol' && <><div className="card-title"><div><h3>OL 자료 검증 및 편집</h3><span>행 단위 직접 입력 · 상태 변경</span></div><div className="button-row"><button className="button" onClick={addOlRow}><Plus size={14} /> 행 추가</button><button className="button" disabled><Upload size={14} /> Excel/CSV 업로드</button></div></div><div className="table-wrap"><table><thead><tr><th>필요월도</th><th>영업부서</th><th>기종코드</th><th>품목명</th><th className="num">OL 수량</th><th>수요상태</th><th>비고</th></tr></thead><tbody>{olRows.map((row) => <tr key={row.id}><td><input className="table-input" value={row.needMonth} onChange={(event) => updateOl(row.id, 'needMonth', event.target.value)} /></td><td><input className="table-input" value={row.department} onChange={(event) => updateOl(row.id, 'department', event.target.value)} /></td><td><input className="table-input" value={row.item} onChange={(event) => updateOl(row.id, 'item', event.target.value)} /></td><td>{row.itemName || <span className="text-danger">품목명 입력 필요</span>}</td><td className="num"><input className="table-input number" type="number" value={row.quantity} onChange={(event) => updateOl(row.id, 'quantity', event.target.value)} /></td><td><select className="table-select" value={row.status} onChange={(event) => updateOl(row.id, 'status', event.target.value)}>{(['확정 후보','조건부','참고','제외'] as DemandStatus[]).map((status) => <option key={status}>{status}</option>)}</select></td><td>{row.note}</td></tr>)}</tbody></table></div></>}
      {tab === 'sfdc' && <><div className="card-title"><div><h3>SFDC 중요 Pipeline</h3><span>수주확률을 기준으로 추가수요 후보를 확인합니다.</span></div><span className="tag blue">{sfdcRows.length}건</span></div><div className="table-wrap"><table><thead><tr><th>Deal ID</th><th>고객명</th><th>기종코드</th><th className="num">예상수량</th><th className="num">수주확률</th><th>Pipeline 상태</th><th>판정</th></tr></thead><tbody>{sfdcRows.map((row) => <tr key={row.id}><td><b>{row.dealId}</b></td><td>{row.customer}</td><td>{row.model}</td><td className="num"><input className="table-input number" type="number" value={row.quantity} onChange={(event) => updateSfdc(row.id, 'quantity', event.target.value)} /></td><td className="num"><input className="table-input number" type="number" min="0" max="100" value={row.probability} onChange={(event) => updateSfdc(row.id, 'probability', event.target.value)} />%</td><td>{row.status}</td><td><span className={`tag ${row.probability >= 70 ? 'green' : 'amber'}`}>{row.probability >= 70 ? '확정 후보' : '검토'}</span></td></tr>)}</tbody></table></div></>}
      {tab === 'bulk' && <><div className="card-title"><div><h3>OL 외 Bulk-deal 수요</h3><span>사전 재고 확보 여부와 발주 반영률을 결정합니다.</span></div><span className="tag amber">조건부 수요</span></div><div className="table-wrap"><table><thead><tr><th>Deal ID</th><th>고객명</th><th>기종코드</th><th className="num">예상수량</th><th>필요월도</th><th>사전재고</th><th>상태</th></tr></thead><tbody>{bulkRows.map((row) => <tr key={row.id}><td><b>{row.dealId}</b></td><td>{row.customer}</td><td>{row.model}</td><td className="num">{row.quantity}</td><td>{row.needMonth}</td><td><button className={`toggle-button ${row.secured ? 'on' : ''}`} onClick={() => setBulkRows((rows) => rows.map((item) => item.id === row.id ? { ...item, secured: !item.secured } : item))}><span>{row.secured ? '확보' : '미확보'}</span></button></td><td><select className="table-select" value={row.status} onChange={(event) => setBulkRows((rows) => rows.map((item) => item.id === row.id ? { ...item, status: event.target.value as DemandStatus } : item))}>{(['확정 후보','조건부','참고','제외'] as DemandStatus[]).map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></>}
      {tab === 'trend' && <><div className="card-title"><div><h3>과거 실적 Trend</h3><span>2025년 월별 실제 출고·사용량 비교 화면</span></div><span className="tag green">12개월 데이터</span></div><div className="grid grid-3"><div className="sample-input"><b>최근 3개월 평균</b><span>기기 284대 · 옵션 118EA</span></div><div className="sample-input"><b>최근 6개월 평균</b><span>기기 276대 · 옵션 113EA</span></div><div className="sample-input"><b>최근 12개월 평균</b><span>기기 269대 · 옵션 109EA</span></div></div><div className="callout blue" style={{ marginTop: 14 }}><BarChart3 size={16} /><div><strong>Trend 비교 결과</strong>현재 대상월도는 전년 동월 대비 기기 출고 +4.8%로, 수요 확정 시 참고 근거로 사용할 수 있습니다.</div></div></>}
      {tab === 'meeting' && <><div className="card-title"><div><h3>수급회의 결과</h3><span>월간 수요 최종 검증 및 확정</span></div><span className={`tag ${confirmed ? 'green' : 'amber'}`}>{confirmed ? '확정 완료' : '회의 결과 입력 중'}</span></div><div className="grid grid-2"><div className="form-stack"><label>회의일<input className="form-input" type="date" value={meeting.date} onChange={(event) => setMeeting({ ...meeting, date: event.target.value })} /></label><label>참석부서<input className="form-input" value={meeting.attendees} onChange={(event) => setMeeting({ ...meeting, attendees: event.target.value })} /></label><label>결정사항<textarea className="form-input" rows={4} value={meeting.decision} onChange={(event) => setMeeting({ ...meeting, decision: event.target.value })} /></label></div><div><div className="callout"><AlertTriangle size={16} /><div><strong>Bulk-deal 사전재고 확보 여부</strong>선택하면 Bulk-deal 조건부 수요를 확정 후보로 반영할 수 있습니다.</div></div><button className={`meeting-toggle ${meeting.secured ? 'selected' : ''}`} onClick={() => setMeeting({ ...meeting, secured: !meeting.secured })}><span className="meeting-check">{meeting.secured && <Check size={13} />}</span>사전재고 확보 결정</button><div className="meeting-result"><div>최종 확정 후보</div><b>{confirmedDemand.toLocaleString()}대</b><span>OL + SFDC 가중 + Bulk 반영</span></div></div></div></>}
    </div>
    <div className="section card demand-actions"><div><div className="card-title"><h3>수요확정 저장 상태</h3><span>{confirmed ? '확정본 생성됨' : validation === 'done' ? '검증 완료' : '작성 중'}</span></div><p className="muted">현재 로컬 프로토타입은 브라우저 화면 상태로 동작합니다. SQLite 저장은 다음 단계에서 연결합니다.</p></div><button className="button primary" onClick={confirmDemand}><Save size={14} /> 확정본 저장</button></div>
  </StepFrame>;
}
