import { Download, FileSpreadsheet, FileText, LockKeyhole, TrendingDown, TrendingUp } from 'lucide-react';
import StepFrame from './step-frame';

export default function ReportStep({ onNext, onBack }: { onNext: () => void; onBack: () => void }) {
  return <StepFrame onNext={onNext} onBack={onBack} nextLabel="전체 현황으로 돌아가기"><div className="page-heading"><div><div className="eyebrow">05 / EXECUTIVE REPORT</div><h2>사장 보고자료</h2><p>총 발주금액과 전월·전년·OL 대비 차이를 설명하는 보고 화면입니다.</p></div><span className="tag blue">보고 미리보기</span></div>
    <div className="grid grid-4"><div className="card metric"><div className="metric-label">당월 총 발주금액</div><div className="metric-value">₩107.2M</div><div className="metric-foot good"><TrendingUp size={12} /> 전월 대비 +8.4%</div></div><div className="card metric"><div className="metric-label">전년 동월 대비</div><div className="metric-value">+3.1%</div><div className="metric-foot">수요 증가 및 재고 보충</div></div><div className="card metric"><div className="metric-label">OL 제출 대비</div><div className="metric-value">+18<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot warn">Bulk-deal 추가 반영</div></div><div className="card metric"><div className="metric-label">주요 감소 품목</div><div className="metric-value">6<span style={{ fontSize: 15, fontWeight: 600 }}>건</span></div><div className="metric-foot"><TrendingDown size={12} /> Open PO 반영</div></div></div>
    <div className="section grid grid-2"><div className="card"><div className="card-title"><h3>발주금액 비교</h3><span>단위: KRW</span></div><div className="table-wrap"><table><thead><tr><th>구분</th><th className="num">전월</th><th className="num">당월</th><th className="num">증감</th></tr></thead><tbody><tr><td>기기</td><td className="num">₩72.4M</td><td className="num"><b>₩91.2M</b></td><td className="num"><span className="tag blue">+26.0%</span></td></tr><tr><td>옵션·부품</td><td className="num">₩26.6M</td><td className="num"><b>₩16.0M</b></td><td className="num"><span className="tag gray">-39.8%</span></td></tr><tr><td><b>합계</b></td><td className="num"><b>₩99.0M</b></td><td className="num"><b>₩107.2M</b></td><td className="num"><span className="tag green">+8.4%</span></td></tr></tbody></table></div></div><div className="card"><div className="card-title"><h3>보고서 미리보기</h3><span>생성 예정</span></div><div className="report-preview"><h4>2026년 09월 발주계획 요약</h4><div className="report-line blue" /><div className="report-line mid" /><div className="report-line" /><div className="report-line short" /><div className="report-line" /></div></div></div>
    <div className="section card"><div className="card-title"><h3>보고서 출력</h3><span>Phase 2에서 활성화</span></div><div className="button-row"><button className="button" disabled><FileSpreadsheet size={14} /> Excel 다운로드</button><button className="button" disabled><FileText size={14} /> PDF 다운로드</button><span className="callout blue" style={{ padding: '9px 12px', flex: 1 }}><LockKeyhole size={15} /><span>계산 결과 확정 후 파일 생성 기능을 연결합니다.</span></span></div></div>
  </StepFrame>;
}
