import { Anchor, Boxes, Check, Clock3, PackageCheck, ShipWheel } from 'lucide-react';
import StepFrame from './step-frame';

export default function SupplyStep({ onNext, onBack }: { onNext: () => void; onBack: () => void }) {
  return <StepFrame onNext={onNext} onBack={onBack} nextLabel="마스터 검증으로 이동"><div className="page-heading"><div><div className="eyebrow">02 / SUPPLY READINESS</div><h2>재고·Open PO 확인</h2><p>전월말 가용재고와 필요월도 전 입고 가능한 Open PO를 발주계산 기준으로 준비합니다.</p></div><span className="tag amber">입력 대기</span></div>
    <div className="grid grid-3"><div className="card metric"><div className="metric-label">전월말 기기 가용재고</div><div className="metric-value">186<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot">정상 가용 상태 기준</div></div><div className="card metric"><div className="metric-label">가용 Open PO</div><div className="metric-value">94<span style={{ fontSize: 15, fontWeight: 600 }}>대</span></div><div className="metric-foot good">필요월도 전 입고 가능</div></div><div className="card metric"><div className="metric-label">납기 위험 Open PO</div><div className="metric-value">2<span style={{ fontSize: 15, fontWeight: 600 }}>건</span></div><div className="metric-foot warn">납기 미확정 · 확인 필요</div></div></div>
    <div className="section grid grid-2"><div className="card"><div className="card-title"><h3>재고 상태별 준비</h3><span>기기·옵션·부품·소모품</span></div><div className="checklist">{[['정상 가용 재고', '반영', 'green'], ['출고 대기 재고', '별도 관리', 'amber'], ['품질 보류·불용 재고', '제외', 'gray'], ['창고별 재고 기준', '확인 필요', 'amber']].map(([label, status, tone]) => <div className="check-row" key={label}><div className="check-label"><span className="check-icon"><Check size={12} /></span>{label}</div><span className={`tag ${tone}`}>{status}</span></div>)}</div></div><div className="card"><div className="card-title"><h3>Open PO 입고 가능성</h3><span>상태·예정월도</span></div><div className="table-wrap"><table><thead><tr><th>PO</th><th>Supplier</th><th>예정월도</th><th>반영</th></tr></thead><tbody><tr><td>PO-260801</td><td>상해</td><td>2026.09</td><td><span className="tag green">가용</span></td></tr><tr><td>PO-260814</td><td>네덜란드</td><td>미정</td><td><span className="tag amber">위험</span></td></tr><tr><td>PO-260818</td><td>도쿄</td><td>2026.10</td><td><span className="tag gray">후속월</span></td></tr></tbody></table></div></div></div>
    <div className="section card"><div className="card-title"><h3>공급망 입력 항목</h3><span>Phase 2에서 활성화</span></div><div className="grid grid-4"><div className="sample-input"><b><Anchor size={14} /> Supplier·공급지역</b><span>상해 · 심천 · 홍콩 · 베트남 · 일본 · 네덜란드</span></div><div className="sample-input"><b><Clock3 size={14} /> Lead Time</b><span>발주부터 한국 도착·창고입고까지</span></div><div className="sample-input"><b><ShipWheel size={14} /> 운송·통관</b><span>현지 선적 및 한국 도착 예정</span></div><div className="sample-input"><b><PackageCheck size={14} /> 검수</b><span>입고수량·상태·Invoice 대사</span></div></div></div>
  </StepFrame>;
}
