-- Backtest 반환 컬럼명과 테이블 컬럼명이 겹치지 않도록 모든 참조를 별칭으로 한정한다.
create or replace function core.run_backtest(p_forecast_run_id uuid)
returns table(backtest_run_id uuid,status text,message text)
language plpgsql security definer set search_path=core,public as $function$
declare setting core.forecast_setting%rowtype; forecast_run core.forecast_run%rowtype; current_run uuid; actor uuid:=auth.uid(); started timestamptz:=clock_timestamp();
begin
  if not core.is_admin() then raise exception 'backtest execution requires ADMIN' using errcode='42501'; end if;
  select * into setting from core.forecast_setting where setting_id='default';
  select * into forecast_run from core.forecast_run where run_id=p_forecast_run_id;
  if forecast_run.run_id is null then raise exception 'forecast run not found'; end if;
  if forecast_run.status <> 'SUCCESS' then raise exception 'forecast run must be SUCCESS'; end if;
  if setting.test_start is null or setting.test_end is null then raise exception 'test setting is incomplete'; end if;
  insert into core.backtest_run(forecast_run_id,test_start,test_end,metric,status,triggered_by,started_at) values(p_forecast_run_id,setting.test_start,setting.test_end,setting.champion_metric,'RUNNING',actor,started) returning core.backtest_run.backtest_run_id into current_run;
  begin
    create temporary table tmp_actual on commit drop as select item_id,date_trunc('month',use_date)::date as period,sum(qty) as actual from core.v_test_actual where use_date between setting.test_start and setting.test_end group by item_id,date_trunc('month',use_date)::date;
    create index tmp_actual_item_period_idx on tmp_actual(item_id,period);
    create temporary table tmp_compare on commit drop as select fr.model_id,fr.model_version,fr.item_id,fr.period,fr.p50 as forecast,ta.actual from core.forecast_result fr left join tmp_actual ta on ta.item_id=fr.item_id and ta.period=fr.period where fr.run_id=p_forecast_run_id and fr.period between date_trunc('month',setting.test_start)::date and date_trunc('month',setting.test_end)::date;
    create temporary table tmp_metric on commit drop as select model_id,max(model_version) as model_version,item_id,count(*) filter(where forecast is not null and actual is not null)::integer as n_periods,sum(abs(forecast-actual)) filter(where forecast is not null and actual is not null) as abs_error_sum,sum(abs(actual)) filter(where forecast is not null and actual is not null) as actual_abs_sum,avg(abs(forecast-actual)) filter(where forecast is not null and actual is not null) as mae,sqrt(avg((forecast-actual)*(forecast-actual)) filter(where forecast is not null and actual is not null)) as rmse,sum(forecast-actual) filter(where forecast is not null and actual is not null) as error_sum,avg(abs((forecast-actual)/nullif(actual,0))*100) filter(where forecast is not null and actual is not null and actual <> 0) as mape,count(*) filter(where forecast is not null and actual is not null and actual <> 0)::integer as mape_periods from tmp_compare group by model_id,item_id;
    create temporary table tmp_ranked on commit drop as select m.*,case when m.actual_abs_sum=0 then null else m.abs_error_sum/m.actual_abs_sum*100 end as wape,case when m.actual_abs_sum=0 then null else m.error_sum/m.actual_abs_sum*100 end as bias,case when m.n_periods=0 then 'NO_COMPARABLE_PERIODS' when m.actual_abs_sum=0 then 'ACTUAL_SUM_ZERO' when m.mape_periods=0 then 'MAPE_NO_VALID_PERIODS' else null end as reason_code,case when m.n_periods>0 and m.actual_abs_sum<>0 then 'SUCCESS' else 'CALCULATION_UNAVAILABLE' end as calculation_status from tmp_metric m;
    insert into core.model_performance(backtest_run_id,forecast_run_id,model_id,model_version,item_id,n_periods,wape,mape,bias,rmse,mae,calculation_status,reason_code) select current_run,p_forecast_run_id,model_id,model_version,item_id,n_periods,wape,mape,bias,rmse,mae,calculation_status,reason_code from tmp_ranked;
    update core.model_performance p set baseline_improvement=case when ref.wape is null or ref.wape=0 or p.wape is null then null else (ref.wape-p.wape)/ref.wape*100 end from core.model_performance ref where p.backtest_run_id=current_run and ref.backtest_run_id=current_run and ref.item_id=p.item_id and ref.model_id=setting.reference_model_id;
    update core.model_performance p set rank=r.rank_no from (select mp.performance_id,row_number() over(partition by mp.item_id order by case when setting.champion_metric='WAPE' then mp.wape when setting.champion_metric='MAPE' then mp.mape when setting.champion_metric='RMSE' then mp.rmse when setting.champion_metric='MAE' then mp.mae when setting.champion_metric='ABS_BIAS' then abs(mp.bias) end asc nulls last,abs(mp.bias) asc nulls last,mp.rmse asc nulls last,mp.model_id) as rank_no from core.model_performance mp where mp.backtest_run_id=current_run and mp.calculation_status='SUCCESS') r where p.performance_id=r.performance_id;
    insert into core.champion_model(item_id,champion_model_id,model_version,champion_metric,champion_metric_value,wape,mape,bias,rmse,candidate_performance,selection_reason,selection_method,reason_code,selected_by) select winner.item_id,winner.model_id,winner.model_version,setting.champion_metric,case when setting.champion_metric='WAPE' then winner.wape when setting.champion_metric='MAPE' then winner.mape when setting.champion_metric='RMSE' then winner.rmse when setting.champion_metric='MAE' then winner.mae when setting.champion_metric='ABS_BIAS' then abs(winner.bias) end,winner.wape,winner.mape,winner.bias,winner.rmse,candidates.candidate_performance,format('%s 기준 최상위 유효 모델(%s)',setting.champion_metric,winner.model_id),'AUTO',null,actor from (select distinct on(mp.item_id) mp.* from core.model_performance mp where mp.backtest_run_id=current_run and mp.calculation_status='SUCCESS' order by mp.item_id,mp.rank) winner join lateral (select jsonb_agg(jsonb_build_object('model_id',p.model_id,'model_version',p.model_version,'wape',p.wape,'mape',p.mape,'bias',p.bias,'rmse',p.rmse,'mae',p.mae,'rank',p.rank,'calculation_status',p.calculation_status,'reason_code',p.reason_code) order by p.rank nulls last,p.model_id) as candidate_performance from core.model_performance p where p.backtest_run_id=current_run and p.item_id=winner.item_id) candidates on true;
    update core.backtest_run b set status='SUCCESS',finished_at=clock_timestamp(),message='Backtest 완료' where b.backtest_run_id=current_run;
  exception when others then
    update core.backtest_run b set status='FAILED',finished_at=clock_timestamp(),message=sqlerrm where b.backtest_run_id=current_run;
  end;
  return query select b.backtest_run_id,b.status,b.message from core.backtest_run b where b.backtest_run_id=current_run;
end; $function$;
revoke all on function core.run_backtest(uuid) from public,anon;
grant execute on function core.run_backtest(uuid) to authenticated;
