create schema if not exists core;
create schema if not exists analytics;

create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(),
  file_name text not null,
  import_type text not null check (import_type in ('usage_history','inventory','item_master','supplier_master','purchase_order','goods_receipt','sales_order','business_event')),
  import_mode text not null check (import_mode in ('append','upsert','replace')),
  total_rows integer not null default 0 check (total_rows >= 0),
  success_rows integer not null default 0 check (success_rows >= 0),
  warning_rows integer not null default 0 check (warning_rows >= 0),
  error_rows integer not null default 0 check (error_rows >= 0),
  status text not null default 'UPLOADED' check (status in ('UPLOADED','PARSED','VALIDATED','VALIDATION_FAILED','APPROVED','IMPORTED','CANCELLED','ROLLED_BACK')),
  replace_confirmed boolean not null default false,
  rollback_supported boolean not null default true,
  uploaded_by uuid not null references auth.users(id),
  uploaded_at timestamptz not null default now(),
  imported_at timestamptz,
  rollback_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists core.import_staging (
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null check (row_number > 0),
  original_row jsonb not null,
  mapped_row jsonb,
  row_status text not null default 'PENDING' check (row_status in ('PENDING','SUCCESS','WARNING','ERROR')),
  created_at timestamptz not null default now(),
  primary key (batch_id, row_number)
);

create table if not exists core.validation_error (
  validation_error_id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null,
  field_name text,
  error_code text not null,
  error_message text not null,
  severity text not null check (severity in ('WARNING','ERROR')),
  original_value text,
  created_at timestamptz not null default now()
);

create table if not exists core.column_mapping (
  import_type text not null,
  source_column text not null,
  target_column text not null,
  confidence numeric(5,4),
  saved_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  primary key (import_type, source_column)
);

alter table raw.forecast add column if not exists data_snapshot_at timestamptz;
alter table raw.forecast add column if not exists stale boolean not null default false;

do $$
declare table_name text;
begin
  foreach table_name in ARRAY ARRAY['usage_history','inventory','item_master','supplier_master','purchase_order','goods_receipt','sales_order','business_event'] loop
    if to_regclass(format('raw.%I', table_name)) is not null then
      execute format('create index if not exists %I on raw.%I(batch_id)', table_name || '_batch_id_idx', table_name);
    end if;
  end loop;
end;
$$;

create or replace view analytics.v_forecast_freshness as
select
  coalesce(bool_or(f.stale), false) as stale,
  max(f.data_snapshot_at) as latest_snapshot_at,
  max(b.imported_at) filter (where b.imported_at is not null) as latest_import_at
from raw.forecast f
left join core.upload_batch b on b.batch_id = f.batch_id;

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.validation_error enable row level security;
alter table core.column_mapping enable row level security;

revoke all on core.upload_batch, core.import_staging, core.validation_error, core.column_mapping from anon;
grant select, insert, update, delete on core.upload_batch, core.import_staging, core.validation_error, core.column_mapping to authenticated;

do $$
declare table_name text;
begin
  foreach table_name in ARRAY ARRAY['upload_batch','import_staging','validation_error','column_mapping'] loop
    execute format('drop policy if exists %I on core.%I', 'import_' || table_name || '_admin', table_name);
    execute format('create policy %I on core.%I for all to authenticated using (core.is_admin()) with check (core.is_admin())', 'import_' || table_name || '_admin', table_name);
  end loop;
end;
$$;

grant select on analytics.v_forecast_freshness to authenticated;
revoke all on analytics.v_forecast_freshness from anon;

create or replace function core.rollback_import_batch(p_batch_id uuid)
returns void
language plpgsql
security invoker
set search_path = core, raw, public
as $$
declare b core.upload_batch%rowtype;
begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select * into b from core.upload_batch where batch_id = p_batch_id for update;
  if b.batch_id is null then raise exception 'BATCH_NOT_FOUND'; end if;
  if b.status <> 'IMPORTED' then raise exception 'BATCH_NOT_IMPORTED'; end if;
  if not b.rollback_supported then raise exception 'ROLLBACK_UNSUPPORTED'; end if;
  execute format('delete from raw.%I where batch_id = $1', b.import_type) using p_batch_id;
  update core.upload_batch set status = 'ROLLED_BACK', rollback_at = now() where batch_id = p_batch_id;
end;
$$;

revoke all on function core.rollback_import_batch(uuid) from public, anon;
grant execute on function core.rollback_import_batch(uuid) to authenticated;
