-- STEP 9: Effective Lead Time 정책 이력과 Forecast 기반 Inventory Projection

alter table core.leadtime_plan add column if not exists effective_from date;
alter table core.leadtime_plan add column if not exists updated_by uuid references auth.users(id);

create table if not exists core.leadtime_plan_history (
  history_id bigint generated by default as identity primary key,
  supplier_id text not null,
  before_value jsonb,
  after_value jsonb not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  change_reason text
);
create index if not exists leadtime_plan_history_supplier_idx on core.leadtime_plan_history(supplier_id, changed_at desc);

create or replace function core.audit_leadtime_plan_change()
returns trigger language plpgsql security definer set search_path = core, public as $$
begin
  insert into core.leadtime_plan_history(supplier_id, before_value, after_value, changed_by, change_reason)
  values (new.supplier_id, case when tg_op = 'UPDATE' then to_jsonb(old) else null end,
          to_jsonb(new), coalesce(new.updated_by, auth.uid()), new.confirmed_reason);
  return new;
end;
$$;
drop trigger if exists leadtime_plan_audit on core.leadtime_plan;
create trigger leadtime_plan_audit after insert or update on core.leadtime_plan
for each row execute function core.audit_leadtime_plan_change();

-- 관리자 확정값이 있으면 우선하고, 없으면 실적 P80을 fallback으로 사용한다.
create or replace view core.v_leadtime_effective as
with suppliers as (
  select distinct "공급업체코드" as supplier_id, "공급업체명" as supplier_name, "국가" as country
  from raw.supplier_master where "사용여부" = 'Y'
), stats as (
  select supplier_id, n_samples, mean_days, p50_days, p80_days, p90_days, confidence
  from core.v_leadtime_stat
)
select s.supplier_id, s.supplier_name, s.country, st.n_samples, st.p80_days,
       p.planned_lead_time,
       case when p.planned_lead_time is not null then p.planned_lead_time else st.p80_days end as effective_lead_time,
       case when p.planned_lead_time is not null then 'ADMIN_CONFIRMED' else 'ACTUAL_P80' end as source,
       st.mean_days, st.p50_days, st.p90_days,
       p.effective_from, p.updated_by,
       case when p.planned_lead_time is not null then null
            when st.n_samples is null or st.n_samples = 0 then 'NO_USAGE_HISTORY'
            when st.n_samples < 10 or st.p80_days is null then 'INSUFFICIENT_SAMPLE'
            else null end as reason_code
from suppliers s left join stats st on st.supplier_id = s.supplier_id
left join core.leadtime_plan p on p.supplier_id = s.supplier_id;

-- 확정수주는 별도 차감하고, Forecast는 확정수주를 뺀 잔여 수요로 저장한다.
drop view if exists analytics.v_stockout_kpi;
drop view if exists analytics.v_stockout_risk;
drop view if exists analytics.v_inventory_projection;
create or replace view analytics.v_inventory_projection as
with recursive
active_items as (
  select item_id, item_name, supplier_id from core.v_item_master where is_active = 'Y'
),
champion_forecast as (
  select distinct on (fr.item_id, fr.period) fr.item_id, fr.period, fr.p50 as champion_p50, r.started_at
  from core.forecast_result fr
  join core.forecast_run r on r.run_id = fr.run_id and r.status = 'SUCCESS'
  left join analytics.v_champion_model cm on cm.item_id = fr.item_id
  left join core.model_config mc on mc.model_id = fr.model_id
  where cm.champion_model_id = fr.model_id or (cm.item_id is null and mc.is_default)
  order by fr.item_id, fr.period, case when cm.champion_model_id = fr.model_id then 0 else 1 end,
           r.started_at desc, fr.run_id desc
),
po_lines as (
  select upper(regexp_replace(po."품목코드", '[\s\-_]', '', 'g')) as item_id,
         nullif(po."납기예정일", '')::date as scheduled_date,
         greatest(0::numeric, nullif(po."발주수량", '')::numeric - coalesce(sum(nullif(gr."입고수량", '')::numeric), 0)) as qty
  from raw.purchase_order po
  left join raw.goods_receipt gr on gr."발주번호" = po."발주번호" and gr."품목코드" = po."품목코드"
  group by po."발주번호", po."품목코드", po."납기예정일", po."발주수량"
),
receipts as (
  select item_id, date_trunc('month', scheduled_date)::date as period, sum(qty) as scheduled_receipt
  from po_lines where scheduled_date is not null and qty > 0 group by item_id, date_trunc('month', scheduled_date)::date
),
confirmed_orders as (
  select upper(regexp_replace(item_id, '[\s\-_]', '', 'g')) as item_id,
         date_trunc('month', coalesce(requested_date, order_date))::date as period, sum(quantity) as confirmed_sales_order
  from raw.sales_order
  where upper(coalesce(status, '')) in ('CONFIRMED', '확정', 'CONFIRMED_ORDER')
    and coalesce(requested_date, order_date) is not null and quantity is not null and quantity > 0
  group by 1, date_trunc('month', coalesce(requested_date, order_date))::date
),
soft_orders as (
  select upper(regexp_replace(item_id, '[\s\-_]', '', 'g')) as item_id,
         date_trunc('month', event_date)::date as period, sum(quantity) as soft_allocation, count(*) as soft_allocation_count
  from raw.business_event
  where upper(coalesce(event_type, '')) in ('SOFT_ALLOCATION', 'SOFT ALLOCATION', '가예약', 'ALLOCATED')
    and event_date is not null and quantity is not null and quantity > 0
  group by 1, date_trunc('month', event_date)::date
),
inventory as (
  select item_id, current_stock from core.v_stock_on_hand
),
forecast_bounds as (
  select item_id, max(period) as last_forecast_period from champion_forecast group by item_id
),
periods as (
  select i.item_id, i.item_name, i.supplier_id, gs.period::date as period
  from active_items i left join forecast_bounds fb on fb.item_id = i.item_id
  cross join lateral generate_series(date_trunc('month', current_date)::date,
    greatest(date_trunc('month', current_date)::date, coalesce(fb.last_forecast_period, date_trunc('month', current_date)::date)), interval '1 month') gs(period)
),
inputs as (
  select p.item_id, p.item_name, p.supplier_id, p.period, i.current_stock,
         coalesce(r.scheduled_receipt, 0::numeric) as scheduled_receipt,
         coalesce(o.confirmed_sales_order, 0::numeric) as confirmed_sales_order,
         coalesce(so.soft_allocation, 0::numeric) as soft_allocation,
         case when so.soft_allocation_count is null then 'DATA_ABSENT' else 'OBSERVED' end as soft_allocation_state,
         cf.champion_p50
  from periods p left join inventory i on i.item_id = p.item_id
  left join receipts r on r.item_id = p.item_id and r.period = p.period
  left join confirmed_orders o on o.item_id = p.item_id and o.period = p.period
  left join soft_orders so on so.item_id = p.item_id and so.period = p.period
  left join champion_forecast cf on cf.item_id = p.item_id and cf.period = p.period
),
projection as (
  select x.item_id, x.item_name, x.supplier_id, x.period, x.current_stock as beginning_inventory,
         x.scheduled_receipt, x.confirmed_sales_order, x.soft_allocation, x.soft_allocation_state,
         case when x.champion_p50 is null then null else greatest(x.champion_p50 - x.confirmed_sales_order, 0::numeric) end as forecast_demand,
         case when x.current_stock is null or x.champion_p50 is null then null else x.current_stock + x.scheduled_receipt - x.confirmed_sales_order - x.soft_allocation - greatest(x.champion_p50 - x.confirmed_sales_order, 0::numeric) end as ending_projected_inventory,
         case when x.current_stock is null then 'NO_INVENTORY_DATA' when x.champion_p50 is null then 'NO_FORECAST' else null end as input_reason
  from inputs x where x.period = (select min(i2.period) from inputs i2 where i2.item_id = x.item_id)
  union all
  select x.item_id, x.item_name, x.supplier_id, x.period, p.ending_projected_inventory,
         x.scheduled_receipt, x.confirmed_sales_order, x.soft_allocation, x.soft_allocation_state,
         case when x.champion_p50 is null then null else greatest(x.champion_p50 - x.confirmed_sales_order, 0::numeric) end,
         case when p.ending_projected_inventory is null or x.champion_p50 is null then null else p.ending_projected_inventory + x.scheduled_receipt - x.confirmed_sales_order - x.soft_allocation - greatest(x.champion_p50 - x.confirmed_sales_order, 0::numeric) end,
         case when p.ending_projected_inventory is null then 'NO_INVENTORY_DATA' when x.champion_p50 is null then 'NO_FORECAST' else null end
  from projection p join inputs x on x.item_id = p.item_id and x.period = (p.period + interval '1 month')::date
),
leadtime as (
  select i.item_id, e.effective_lead_time, e.source as leadtime_source, e.reason_code as leadtime_reason
  from active_items i left join core.v_leadtime_effective e on e.supplier_id = i.supplier_id
),
marked as (
  select p.*, l.effective_lead_time, l.leadtime_source, l.leadtime_reason,
         min(p.period) filter (where p.ending_projected_inventory <= 0) over (partition by p.item_id) as stockout_period,
         sum(p.forecast_demand) over (partition by p.item_id) as forecast_total
  from projection p left join leadtime l on l.item_id = p.item_id
),
metrics as (
  select m.*, case when m.stockout_period is not null and m.period = m.stockout_period then greatest(0, (m.stockout_period - current_date))::numeric end as row_days_to_stockout
  from marked m
)
select item_id, item_name, supplier_id, period, beginning_inventory, scheduled_receipt, confirmed_sales_order,
       soft_allocation, soft_allocation_state, forecast_demand, ending_projected_inventory, stockout_period,
       stockout_period as stockout_date, row_days_to_stockout as days_of_supply,
       case when row_days_to_stockout is null then null else round(row_days_to_stockout / 30, 1) end as months_of_supply,
       effective_lead_time, leadtime_source, leadtime_reason,
       case when beginning_inventory is null then 'CALCULATION_UNAVAILABLE' when forecast_demand is null then 'CALCULATION_UNAVAILABLE' else 'SUCCESS' end as calculation_status,
       case when beginning_inventory is null then 'NO_INVENTORY_DATA' when forecast_demand is null then 'NO_FORECAST' when leadtime_reason is not null then leadtime_reason else null end as reason_code,
       case when beginning_inventory is null or forecast_demand is null or effective_lead_time is null then 'CALCULATION_UNAVAILABLE'
            when stockout_period is null then 'SAFE'
            when stockout_period < date_trunc('month', current_date + make_interval(days => effective_lead_time::integer))::date then 'CRITICAL'
            else 'WARNING' end as risk_status
from metrics;

create or replace view analytics.v_stockout_risk as
with first_rows as (
  select distinct on (item_id) item_id, item_name, supplier_id, beginning_inventory as current_stock,
         effective_lead_time as planned_lead_time, stockout_period, stockout_date, days_of_supply, months_of_supply, risk_status, reason_code
  from analytics.v_inventory_projection order by item_id, period
), inbound as (
  select item_id, sum(scheduled_receipt) as inbound_qty from analytics.v_inventory_projection group by item_id
)
select f.item_id, f.item_name, f.supplier_id, f.current_stock, i.inbound_qty, f.stockout_date, f.stockout_period,
       f.planned_lead_time, f.days_of_supply, f.months_of_supply, f.risk_status, f.reason_code
from first_rows f left join inbound i using (item_id);

create or replace view analytics.v_stockout_kpi as
select count(*)::integer as n_items, count(*) filter (where risk_status = 'CRITICAL')::integer as n_critical,
       count(*) filter (where risk_status = 'WARNING')::integer as n_warning,
       count(*) filter (where risk_status = 'SAFE')::integer as n_safe,
       count(*) filter (where risk_status = 'CALCULATION_UNAVAILABLE')::integer as n_calculation_unavailable,
       count(*) filter (where days_of_supply is not null and days_of_supply <= 30)::integer as n_within_30d,
       round(avg(days_of_supply), 1) as avg_stockout_days
from analytics.v_stockout_risk;

alter table core.leadtime_plan enable row level security;
alter table core.leadtime_plan_history enable row level security;
revoke all on core.leadtime_plan, core.leadtime_plan_history from anon, authenticated;
grant select on core.leadtime_plan_history, core.leadtime_plan to authenticated;
grant select on core.v_leadtime_effective to authenticated;
drop policy if exists leadtime_plan_admin on core.leadtime_plan;
create policy leadtime_plan_admin on core.leadtime_plan for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists leadtime_plan_history_select on core.leadtime_plan_history;
create policy leadtime_plan_history_select on core.leadtime_plan_history for select to authenticated using (true);
grant select on analytics.v_inventory_projection, analytics.v_stockout_risk, analytics.v_stockout_kpi to authenticated;
revoke all on analytics.v_inventory_projection, analytics.v_stockout_risk, analytics.v_stockout_kpi from anon;
