create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  department text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

insert into core.app_user(user_id, email, name)
select id, coalesce(email, ''), coalesce(raw_user_meta_data ->> 'name', '')
from auth.users
on conflict (user_id) do update set email = excluded.email;

create index if not exists app_user_role_active_idx on core.app_user(role, active);
create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id, at desc);

create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select exists (
    select 1 from core.app_user
    where user_id = auth.uid()
      and role = 'ADMIN'
      and active = true
  );
$$;

revoke all on function core.is_admin() from public;
grant execute on function core.is_admin() to authenticated;

create or replace function core.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  insert into core.app_user(user_id, email, name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'name', ''))
  on conflict (user_id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function core.handle_new_auth_user();

create or replace function core.set_app_user_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at
  before update on core.app_user
  for each row execute function core.set_app_user_updated_at();

create or replace function core.prevent_self_privilege_change()
returns trigger
language plpgsql
as $$
begin
  if auth.uid() = old.user_id
     and (new.role is distinct from old.role or new.active is distinct from old.active) then
    raise exception 'self privilege change is not allowed' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists app_user_prevent_self_privilege_change on core.app_user;
create trigger app_user_prevent_self_privilege_change
  before update on core.app_user
  for each row execute function core.prevent_self_privilege_change();

create or replace function core.audit_app_user_change()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  if old.role is distinct from new.role or old.active is distinct from new.active then
    insert into core.audit_log(actor, action, target_type, target_id, before, after)
    values (
      auth.uid(),
      case when old.role is distinct from new.role then 'USER_ROLE_CHANGED' else 'USER_STATUS_CHANGED' end,
      'app_user',
      new.user_id::text,
      jsonb_build_object('role', old.role, 'active', old.active),
      jsonb_build_object('role', new.role, 'active', new.active)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists app_user_audit_change on core.app_user;
create trigger app_user_audit_change
  after update on core.app_user
  for each row execute function core.audit_app_user_change();

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;

revoke all on schema core from anon;
revoke all on all tables in schema core from anon;
revoke all on all sequences in schema core from anon;
grant usage on schema core to authenticated;
grant select on core.app_user to authenticated;
grant update on core.app_user to authenticated;
grant select on core.audit_log to authenticated;

drop policy if exists app_user_select_self_or_admin on core.app_user;
create policy app_user_select_self_or_admin
  on core.app_user for select to authenticated
  using (user_id = auth.uid() or core.is_admin());

drop policy if exists app_user_admin_update on core.app_user;
create policy app_user_admin_update
  on core.app_user for update to authenticated
  using (core.is_admin())
  with check (core.is_admin());

drop policy if exists audit_log_admin_select on core.audit_log;
create policy audit_log_admin_select
  on core.audit_log for select to authenticated
  using (core.is_admin());

revoke insert, update, delete on core.audit_log from anon, authenticated;


-- 분석 화면에 필요한 뷰만 authenticated 읽기를 허용한다.
create schema if not exists analytics;
revoke all on schema analytics from anon;
grant usage on schema analytics to authenticated;
do $$
begin
  if to_regclass('analytics.v_leadtime_gap') is not null and to_regclass('analytics.v_stockout_kpi') is not null and to_regclass('analytics.v_stockout_risk') is not null then
    revoke all on analytics.v_leadtime_gap, analytics.v_stockout_kpi, analytics.v_stockout_risk from anon;
    grant select on analytics.v_leadtime_gap, analytics.v_stockout_kpi, analytics.v_stockout_risk to authenticated;
  end if;
end;
$$;
