-- STEP 7 Backtest: 저장된 Forecast Result와 검증 Actual만 비교한다.
alter table if exists core.forecast_setting add column if not exists champion_metric text not null default 'WAPE';
alter table if exists core.forecast_setting add column if not exists reference_model_id text not null default 'MA_3M';
do $$ begin
  if to_regclass('core.forecast_setting') is not null then
    alter table core.forecast_setting drop constraint if exists forecast_setting_champion_metric;
    alter table core.forecast_setting add constraint forecast_setting_champion_metric check (champion_metric in ('WAPE','MAPE','RMSE','MAE','ABS_BIAS'));
  end if;
end $$;

create table if not exists core.backtest_run (
  backtest_run_id uuid primary key default gen_random_uuid(),
  forecast_run_id uuid not null references core.forecast_run(run_id) on delete restrict,
  test_start date not null, test_end date not null,
  metric text not null, status text not null check (status in ('RUNNING','SUCCESS','FAILED')),
  started_at timestamptz not null default now(), finished_at timestamptz,
  triggered_by uuid references auth.users(id), message text
);
create table if not exists core.model_performance (
  performance_id bigint generated by default as identity primary key,
  backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete cascade,
  forecast_run_id uuid not null references core.forecast_run(run_id) on delete restrict,
  model_id text not null, model_version text, item_id text not null,
  n_periods integer not null default 0, wape numeric, mape numeric, bias numeric,
  rmse numeric, mae numeric, baseline_improvement numeric, rank integer,
  calculation_status text not null check (calculation_status in ('SUCCESS','CALCULATION_UNAVAILABLE')),
  reason_code text, calculated_at timestamptz not null default now(),
  unique(backtest_run_id,model_id,item_id)
);
create table if not exists core.champion_model (
  champion_id bigint generated by default as identity primary key,
  item_id text not null, champion_model_id text not null, model_version text,
  champion_metric text not null, champion_metric_value numeric,
  wape numeric, mape numeric, bias numeric, rmse numeric,
  candidate_performance jsonb not null default '[]'::jsonb,
  selection_reason text, selection_method text not null check (selection_method in ('AUTO','MANUAL')),
  reason_code text, selected_at timestamptz not null default now(), selected_by uuid references auth.users(id)
);
create index if not exists backtest_run_forecast_idx on core.backtest_run(forecast_run_id, started_at desc);
create index if not exists model_performance_item_idx on core.model_performance(item_id, calculated_at desc);
create index if not exists champion_model_current_idx on core.champion_model(item_id, selected_at desc);
comment on column core.model_performance.bias is 'Bias = sum(forecast - actual) / sum(abs(actual)) * 100. 양수는 과대예측, 음수는 과소예측.';
comment on column core.model_performance.mape is 'Actual=0 기간은 분모에서 제외한다. 유효 기간이 없으면 NULL.';

create or replace function core.run_backtest(p_forecast_run_id uuid)
returns table(backtest_run_id uuid,status text,message text)
language plpgsql security definer set search_path=core,public as $function$
declare
  setting core.forecast_setting%rowtype; forecast_run core.forecast_run%rowtype;
  current_run uuid; actor uuid:=auth.uid(); started timestamptz:=clock_timestamp();
begin
  if not core.is_admin() then raise exception 'backtest execution requires ADMIN' using errcode='42501'; end if;
  select * into setting from core.forecast_setting where setting_id='default';
  select * into forecast_run from core.forecast_run where run_id=p_forecast_run_id;
  if forecast_run.run_id is null then raise exception 'forecast run not found'; end if;
  if forecast_run.status <> 'SUCCESS' then raise exception 'forecast run must be SUCCESS'; end if;
  if setting.test_start is null or setting.test_end is null then raise exception 'test setting is incomplete'; end if;
  insert into core.backtest_run(forecast_run_id,test_start,test_end,metric,status,triggered_by,started_at)
  values(p_forecast_run_id,setting.test_start,setting.test_end,setting.champion_metric,'RUNNING',actor,started)
  returning core.backtest_run.backtest_run_id into current_run;
  begin
    create temporary table tmp_actual on commit drop as
      select item_id,date_trunc('month',use_date)::date as period,sum(qty) as actual
      from core.v_test_actual
      where use_date between setting.test_start and setting.test_end
      group by item_id,date_trunc('month',use_date)::date;
    create index tmp_actual_item_period_idx on tmp_actual(item_id,period);
    create temporary table tmp_compare on commit drop as
      select fr.model_id,fr.model_version,fr.item_id,fr.period,fr.p50 as forecast,ta.actual
      from core.forecast_result fr left join tmp_actual ta on ta.item_id=fr.item_id and ta.period=fr.period
      where fr.run_id=p_forecast_run_id and fr.period between date_trunc('month',setting.test_start)::date and date_trunc('month',setting.test_end)::date;
    create temporary table tmp_metric on commit drop as
      select model_id,max(model_version) as model_version,item_id,
        count(*) filter(where forecast is not null and actual is not null)::integer as n_periods,
        sum(abs(forecast-actual)) filter(where forecast is not null and actual is not null) as abs_error_sum,
        sum(abs(actual)) filter(where forecast is not null and actual is not null) as actual_abs_sum,
        avg(abs(forecast-actual)) filter(where forecast is not null and actual is not null) as mae,
        sqrt(avg((forecast-actual)*(forecast-actual)) filter(where forecast is not null and actual is not null)) as rmse,
        sum(forecast-actual) filter(where forecast is not null and actual is not null) as error_sum,
        avg(abs((forecast-actual)/nullif(actual,0))*100) filter(where forecast is not null and actual is not null and actual <> 0) as mape,
        count(*) filter(where forecast is not null and actual is not null and actual <> 0)::integer as mape_periods
      from tmp_compare group by model_id,item_id;
    create temporary table tmp_ranked on commit drop as
      select m.*,case when m.actual_abs_sum=0 then null else m.abs_error_sum/m.actual_abs_sum*100 end as wape,
        case when m.actual_abs_sum=0 then null else m.error_sum/m.actual_abs_sum*100 end as bias,
        case when m.n_periods=0 then 'NO_COMPARABLE_PERIODS' when m.actual_abs_sum=0 then 'ACTUAL_SUM_ZERO' when m.mape_periods=0 then 'MAPE_NO_VALID_PERIODS' else null end as reason_code,
        case when m.n_periods>0 and m.actual_abs_sum<>0 then 'SUCCESS' else 'CALCULATION_UNAVAILABLE' end as calculation_status
      from tmp_metric m;
    insert into core.model_performance(backtest_run_id,forecast_run_id,model_id,model_version,item_id,n_periods,wape,mape,bias,rmse,mae,calculation_status,reason_code)
      select current_run,p_forecast_run_id,model_id,model_version,item_id,n_periods,wape,mape,bias,rmse,mae,calculation_status,reason_code from tmp_ranked;
    update core.model_performance p set baseline_improvement=case when ref.wape is null or ref.wape=0 or p.wape is null then null else (ref.wape-p.wape)/ref.wape*100 end
      from core.model_performance ref where p.backtest_run_id=current_run and ref.backtest_run_id=current_run and ref.item_id=p.item_id and ref.model_id=setting.reference_model_id;
    update core.model_performance p set rank=r.rank_no
      from (select performance_id,row_number() over(partition by item_id order by
        case when setting.champion_metric='WAPE' then wape when setting.champion_metric='MAPE' then mape when setting.champion_metric='RMSE' then rmse when setting.champion_metric='MAE' then mae when setting.champion_metric='ABS_BIAS' then abs(bias) end asc nulls last,
        abs(bias) asc nulls last,rmse asc nulls last,model_id) as rank_no
        from core.model_performance where backtest_run_id=current_run and calculation_status='SUCCESS') r
      where p.performance_id=r.performance_id;
    insert into core.champion_model(item_id,champion_model_id,model_version,champion_metric,champion_metric_value,wape,mape,bias,rmse,candidate_performance,selection_reason,selection_method,reason_code,selected_by)
      select winner.item_id,winner.model_id,winner.model_version,setting.champion_metric,
        case when setting.champion_metric='WAPE' then winner.wape when setting.champion_metric='MAPE' then winner.mape when setting.champion_metric='RMSE' then winner.rmse when setting.champion_metric='MAE' then winner.mae when setting.champion_metric='ABS_BIAS' then abs(winner.bias) end,
        winner.wape,winner.mape,winner.bias,winner.rmse,candidates.candidate_performance,
        format('%s 기준 최상위 유효 모델(%s)',setting.champion_metric,winner.model_id),'AUTO',null,actor
      from (select distinct on(item_id) * from core.model_performance where backtest_run_id=current_run and calculation_status='SUCCESS' order by item_id,rank) winner
      join lateral (select jsonb_agg(jsonb_build_object('model_id',p.model_id,'model_version',p.model_version,'wape',p.wape,'mape',p.mape,'bias',p.bias,'rmse',p.rmse,'mae',p.mae,'rank',p.rank,'calculation_status',p.calculation_status,'reason_code',p.reason_code) order by p.rank nulls last,p.model_id) as candidate_performance from core.model_performance p where p.backtest_run_id=current_run and p.item_id=winner.item_id) candidates on true;
    update core.backtest_run set status='SUCCESS',finished_at=clock_timestamp(),message='Backtest 완료' where core.backtest_run.backtest_run_id=current_run;
  exception when others then
    update core.backtest_run set status='FAILED',finished_at=clock_timestamp(),message=sqlerrm where core.backtest_run.backtest_run_id=current_run;
  end;
  return query select b.backtest_run_id,b.status,b.message from core.backtest_run b where b.backtest_run_id=current_run;
end; $function$;

create or replace function core.set_manual_champion(p_item_id text,p_model_id text,p_reason text)
returns table(champion_id bigint,status text)
language plpgsql security definer set search_path=core,public as $function$
declare actor uuid:=auth.uid(); p core.model_performance%rowtype; cid bigint;
begin
  if not core.is_admin() then raise exception 'manual champion requires ADMIN' using errcode='42501'; end if;
  if nullif(trim(coalesce(p_reason,'')),'') is null then raise exception 'manual champion reason is required'; end if;
  select * into p from core.model_performance where item_id=p_item_id and model_id=p_model_id and calculation_status='SUCCESS' order by calculated_at desc limit 1;
  if p.performance_id is null then raise exception 'no valid performance found for item/model'; end if;
  insert into core.champion_model(item_id,champion_model_id,model_version,champion_metric,champion_metric_value,wape,mape,bias,rmse,candidate_performance,selection_reason,selection_method,reason_code,selected_by)
    select p.item_id,p.model_id,p.model_version,s.champion_metric,case when s.champion_metric='WAPE' then p.wape when s.champion_metric='MAPE' then p.mape when s.champion_metric='RMSE' then p.rmse when s.champion_metric='MAE' then p.mae when s.champion_metric='ABS_BIAS' then abs(p.bias) end,p.wape,p.mape,p.bias,p.rmse,'[]'::jsonb,p_reason,'MANUAL',null,actor from core.forecast_setting s returning champion_model.champion_id into cid;
  insert into core.audit_log(actor,action,target_type,target_id,before,after) values(actor,'CHAMPION_MANUALLY_CHANGED','champion_model',p_item_id,jsonb_build_object('model_id',(select champion_model_id from core.champion_model where item_id=p_item_id and champion_id<>cid order by selected_at desc limit 1)),jsonb_build_object('model_id',p_model_id,'reason',p_reason,'champion_id',cid));
  return query select cid,'SUCCESS'::text;
end; $function$;

create or replace view analytics.v_backtest_run as select b.*,u.email as triggered_email from core.backtest_run b left join core.app_user u on u.user_id=b.triggered_by;
create or replace view analytics.v_model_performance as select * from core.model_performance;
create or replace view analytics.v_champion_model as select distinct on(item_id) * from core.champion_model order by item_id,selected_at desc,champion_id desc;
create or replace view analytics.v_model_comparison as
select fr.run_id,fr.model_id,fr.model_version,fr.item_id,fr.period,fr.p50,fr.p80,fr.p90,ta.actual,mp.wape,mp.mape,mp.bias,mp.rmse,mp.mae,mp.rank,cm.champion_model_id=(fr.model_id) as is_champion
from core.forecast_result fr
left join (select item_id,date_trunc('month',use_date)::date as period,sum(qty) as actual from core.v_test_actual group by item_id,date_trunc('month',use_date)::date) ta on ta.item_id=fr.item_id and ta.period=fr.period
left join analytics.v_model_performance mp on mp.forecast_run_id=fr.run_id and mp.model_id=fr.model_id and mp.item_id=fr.item_id
left join analytics.v_champion_model cm on cm.item_id=fr.item_id;

alter table core.backtest_run enable row level security;
alter table core.model_performance enable row level security;
alter table core.champion_model enable row level security;
revoke all on core.backtest_run,core.model_performance,core.champion_model from anon,authenticated;
grant select on analytics.v_backtest_run,analytics.v_model_performance,analytics.v_champion_model,analytics.v_model_comparison to authenticated;
revoke all on analytics.v_backtest_run,analytics.v_model_performance,analytics.v_champion_model,analytics.v_model_comparison from anon;
grant execute on function core.run_backtest(uuid) to authenticated;
grant execute on function core.set_manual_champion(text,text,text) to authenticated;
